### ISSUE TITLE
Deselecting "Show row numbers in hex" in the config dialogue does nothing.

### ISSUE THREAD

**Issue by Midi-In** [rerrahkr/BambooTracker#176]
Pretty much what the title says, unticking the checkbox has no effect on the pattern viewport.
Observed on Windows XP SP3 Professional 32 bit

**Comment by Midi-In** [comment]
Correction: It only does affect the sequence order window, which i couldn't notice, not having checked that with any module loaded/composed, thus only having a single entry in there.

Still, that's very inconsistent, and maybe you should consider to make it affect all instances of numbering throughout the tracker (I could open a feature request for that, but no point in cluttering more, and I'm actually not sure whether to see it as a bug or an intender behaviour)?

**Comment by rerrahkr** [comment]
Thank you for your report.
BambooTracker described about this feature in the configuration dialog:
> Display **order numbers** and the order count on the status bar in hexadecimal.

But I have checked the same settings of 0CC-FamiTracker, that BambooTracker is based on, it changes pattern row number too. So it is necessary to change the behavior of hex/decimal switch.

About consistency, I keep some numbers like tempo in decimal because there are no major problems about it with FamiTracker and Deflemask. I also think differences in behavior from them can cause confusion.

**Comment by rerrahkr** [comment]
I changed the behavior to display pattern step number in decimal at b492a76ae28ab551da254ddcb83b059c5e1f0ab1.

**Comment by Midi-In** [comment]
Thank you!
