### ISSUE TITLE
Cloning an instrument permanently disable creating a new instrument

### ISSUE THREAD

**Issue by Pigu-A** [rerrahkr/BambooTracker#177]

**Comment by rerrahkr** [comment]
Thanks for your report.
Does it happen when you have many instruments in the instrument list? Up to 127 instruments can be added to the list, and the tracker ignores instrument addition and cloning when the list is filled.

If your report doesn't match this, that is an unknown bug, could you please elaborate the situation where the problem occurred?

**Comment by nyanpasu64** [comment]
The description of the bug is inaccurate.

- In the pattern editor, highlight a rhythm channel.
- Focus a different instrument in the instrument editor.

There are many ways to focus a different instrument:

- Left-click or right-click another instrument.
- Delete an instrument so focus moves to another instrument.
- Clone the current instrument, then left-click the copy. Actually cloning is unrelated to the bug.

The Add Instrument button is disabled until you close the program. Focusing a non-rhythm channel then switching instruments doesn't re-enable the button.

I think the button should be automatically disabled as soon as you focus a rhythm channel, and automatically enabled as soon as you focus a non-rhythm channel.

BambooTracker-v0.3.5.33-dev

**Comment by pedipanol** [comment]
This also happens when importing a .PPC or .PVI sample bank

Em Ter, 17 de mar de 2020 02:17, nyanpasu64 <notifications@github.com>
escreveu:

**Comment by rerrahkr** [comment]
I figured out that, thank you! At 159b813212adb9ddd1bc0da1778e8a20d4b22a26, I fixed the tracker to check whether you can add a new instrument when changing the current track, that resolve this issue.
