### ISSUE TITLE
FM Channel 2 goes silent under certain occasion

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#182]
[fury.zip](https://github.com/rerrahkr/BambooTracker/files/4239657/fury.zip) - extremely early WIP cover, yet anyway - on pattern 0A, instrument that's played on FM2 goes silent. The only way to make it play as intended is to pause the song and play it once again - then it will work fine.

**Comment by rerrahkr** [comment]
In step 60, pattern 06 of ch.2, you set the tone portamento effect `0382` and there is no stop portamento effect `0300` after this step. All note-on events are ignored during tone portamento, and tone portamento is enabled by channel retrieving on starting the playback, so that this issue is happened. It will work correctly by setting `0300` in appropriate place.

BTW it is inconvenient a little that BambooTracker ignores even the first note-on when tone portamento is set before the playing start position, I will change the first note-on controls about tone portamento.

**Comment by freq-mod** [comment]
You're right, I forgot about that `0382`. Sorry about that.
> I will change the first note-on controls about tone portamento. 

Done as of fa4c0bf.
