### ISSUE TITLE
Sample "Memory" not cleaned upon ADPCM instrument deletion

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#186]
Expectation:
--
Instances where deleting an instrument will remove the last reference will automatically free the memory (displayed in the ADPCM instrument editor) that's associated with the sample & reorganize the memory.

Reality:
--
Deleting an instrument like that currently doesn't free the memory. Loading a (PPC) bank, deleting a few instruments and loading another bank does not help with fitting the second bank into memory.
Even worse, it seems this can cause a sample to play back the entirety of memory. I [appended a module](https://github.com/rerrahkr/BambooTracker/files/4269450/ADPCMMemoryWeirdness.zip) where I:

1. Loaded a bank
2. Deleted some of the first instrument
3. Loaded another bank

Instruments 00 - 04 sound fine, but reference sections at the very end of memory. Instrument 5 however plays the entirety of memory, including the contents of the first bank that are inaccessible in memory.

Selecting Module->Cleanup->Remove unused instruments finally frees up the memory.

**Comment by rerrahkr** [comment]
Thanks for your request.

> Deleting an instrument like that currently doesn't free the memory.

This is due to consistency with other instrument property operations like arpeggio. When adding new instrument using properties, BambooTracker copies properties to property list, where it is unused and not edited property area.
I have a plan to add a new selection in the configuration: whether BambooTracker assign properties to **unused** or **unused and not edited** property area. If you selected "unused" and import a ADPCM sample, it is stored to the memory area unused by any instrument.

**Comment by rerrahkr** [comment]
I also will add a selection to store only used samples to memory, more close to what you suggested.

**Comment by rerrahkr** [comment]
I added selection in the configuration to store only used samples to the memory at 80b447e01abcaa4daa8f90856dd4b9058631cc9b. Do not change the memory frequently, as it is a bit heavy.
