### ISSUE TITLE
Text-based module format, compatible with git diff?

### ISSUE THREAD

**Issue by nyanpasu64** [rerrahkr/BambooTracker#19]
Are you interested in adding a text-based export format like FT? Possibly as a native open/save file format (not just import/export) so opening a text and pressing Ctrl+S produces a text file instead of .btm?

Things I would improve from FT text export:

- 1:1 mapping between orders and visible text (achievable through https://github.com/rerrahkr/BambooTracker/issues/14 )
- Removing pattern numbers? Maybe makes diff/merge easier, maybe makes parsing complicated and error-prone.

**Comment by rerrahkr** [comment]
I'm sorry to reply after really a long time.
Personally, I don't feel the need to implement it because the file size is larger than btm and I don't see the module published in text format in other trackers.
However, I do think that being able to read it with the human eye is an advantage.
It's closed for now, but in some cases I may implement it in the future.
