### ISSUE TITLE
Shortcuts for changing octave do not work

### ISSUE THREAD

**Issue by SMB7** [rerrahkr/BambooTracker#192]
The shortcuts for changing the base octave up or down (default `*` and `/`) have no effect. Similar to old issue #55 (main keyboard `/` works while numpad `/` and both variants of `*` do not), but the suggested workaround of rebinding the keys also has no effect for most keys. Currently I have them set to `;` up and `/` down, which does work. (This is occurring in dev build 0.3.5.39, I recall it also happening in release version of 0.3.5.)

**Comment by rerrahkr** [comment]
Thanks for your report. The bug was caused by the mismatch between the shortcut key sequence set in the configuration and that detected internally. After a little research, I noticed that there is a class that handles shortcuts in the Qt library, so I will replace the existing shortcut processing with it.

**Comment by rerrahkr** [comment]
> I noticed that there is a class that handles shortcuts in the Qt library

It works well as far as I checked 0982f6ba8b3a7cb420ea16de0fa601e18fd08bbe.

**Comment by SMB7** [comment]
Works as expected in 0f529500. Thank you!
