### ISSUE TITLE
Some tfi/vgi patches have a "Out of range dt" error when loading

### ISSUE THREAD

**Issue by YoshiLightStar** [rerrahkr/BambooTracker#194]
Some of my tfi/vgi patch collection cannot be loaded due to this error, I have confirmed that they work in Megadrive programs that work with these file types(Such as Deflemask,Genny VST,VGM Music Maker etc). The files do work if I then convert them to Deflemask(.DMP) but that is tedious because I have a big collection of tfi/vgi files is there a way to get these working without conversion? Example included was obtained by converting a opm file to tfi with vopmxtfi(Like some of my tfi/vgi collection)
[DX7 EP .tfi.zip](https://github.com/rerrahkr/BambooTracker/files/4366815/DX7.EP.tfi.zip)

**Comment by rerrahkr** [comment]
Thanks for your report. I've just check your file and found out that detune value is set as $07. According to [VGI spec](https://vgmrips.net/wiki/VGI_File_Format#Detune_values) and [TFI spec](https://vgmrips.net/wiki/TFI_File_Format#Detune_values), this is an undefined value, so that perhaps it is the problem of tfi/vgi patch generator you used.
However, many tracker allow to load this value (maybe a famous bug?), I will make BambooTracker to modify an error detune automatically in importing tfi/vgi.

**Comment by rerrahkr** [comment]
> I will make BambooTracker to modify an error detune automatically in importing tfi/vgi.

I fixed it at 08cf2110ab91a22ff1b8985914853e59bc7ccb16.
