### ISSUE TITLE
ADPCM import keeps failing

### ISSUE THREAD

**Issue by Drillimation** [rerrahkr/BambooTracker#224]
I'm trying to import the ADPCM file and it keeps failing.

**Comment by rerrahkr** [comment]
Is an ADPCM file a WAV file? WAV only supports 16-bit mono 2k-16kHz samples in BambooTracker.

**Comment by freq-mod** [comment]
Most likely unrelated, but when importing .wav file with filename containing _mojibake_ (and being quite large), following error message popped up:
![Przechwytywanie](https://user-images.githubusercontent.com/32672779/85290373-2ad7c080-b499-11ea-820a-bb60a3d58213.JPG)

However, sample import was successful, it loaded albeit cut short due to 256kB memory limit, which is understandable.

**Comment by rerrahkr** [comment]
I haven't checked it in detail, but if the sample is too long, it may not fit in memory and an error may occur.

**Comment by rerrahkr** [comment]
I don't know the detailed situation about the main issue, so I close it.
Please reopen if there is a follow-up report.
