### ISSUE TITLE
[Question] License of non library parts

### ISSUE THREAD

**Issue by rerrahkr** [rerrahkr/BambooTracker#266]
BambooTracker is distributed under GPL v2 because it uses the MAME code of VGMPlay. It also follows the licenses listed in [the list for the libraries it uses](https://github.com/rerrahkr/BambooTracker/blob/master/licenses/list.md).

Is it possible to set a license such as MIT only for the source of other parts (for example, Playback process and instrument class)?
Also, if that is possible, is it correct to recognize that if only the MIT part is used in another project, the license corresponding to that part will be applied instead of the GPL?

**Comment by superctr** [comment]
You're free to assign any license to the parts that you have developed, since you own the copyright to the parts you have the developed. The GPL cannot take away that from you, but by using GPL components you would be obliged to license the complete program (that is all components once together) under the GPL and to make sure that all subcomponents are compatible with the GPL license.

So, in other words, you can license the other parts of the project under the MIT license or any other, as long as it is compatible with the GPL. To make it clear I would specify the license used in the beginning of each file.

**Comment by rerrahkr** [comment]
Thanks for your advice! I wonder if my code will be useful to someone, but I'll set a license to the rest of the parts. Probably MIT license.
At least I'll write the license statement at the beginning of the file I made.
