### ISSUE TITLE
[Linux] - Selecting Dummy MIDI attempts to initialize ALSA MIDI first

### ISSUE THREAD

**Issue by OPNA2608** [rerrahkr/BambooTracker#278]
> #### Checklist
> 
> 
> 
> - [x] I am reporting exactly 1 bug with this issue.
> - [x] This bug hasn't already been reported.
> - [x] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

Attempting to use the `Dummy` MIDI API will try to initialize the `ALSA` MIDI API first. While usually harmless, this will cause an error message when the `ALSA`-based MIDI API is unavailable on the current system (`snd_seq` kernel module / `/dev/snd/seq` device missing).

As a minor complaint, the hardcoded `[Midi Out]` indicator in [BambooTracker/midi/midi.cpp:312](https://github.com/rerrahkr/BambooTracker/blob/0e5f571f7e31527adb2b73e083b961ae798f6342/BambooTracker/midi/midi.cpp#L312) is irritating because the same method is also used as the error handler for MIDI-IN, and it doesn't fit to the rest of BT's error messages (which never indicate any component in particular). I think it's a good idea though, so it might be worth to check if that can somehow be centralized & used throughout BT for terminal-based outputs?

## How to reproduce

1. Start a system without the `snd_seq` kernel module
2. Launch BambooTracker
- If your last configured MIDI API was `Dummy`, there will already be an error message on start-up
- If not, head to `Configuration -> Sound` and try to apply the `Dummy` MIDI API

## System Information

- **Operating System**: postmarketOS 1.23.0 aarch64
- **BambooTracker Version**: first-pattern-draw 113087eec388e64d65fc9adf7e3fa2a4df510a65 (also happening before that)
- **Build Type**: locally

**Comment by rerrahkr** [comment]
Thanks for your report.

https://github.com/rerrahkr/BambooTracker/blob/b8cd8c88939710a143c9000d091f97b4656966c9/BambooTracker/midi/midi.cpp#L42-L49

I set `RtMidi::UNSPECIFIED` which `Search for a working compiled API` in the constructor, so I will change this to `RtMidi::RTMIDI_DUMMY`.

I also remove code related to MIDI output since BambooTracker has no plan to support it.
I'm trying to change the current callback for error handling to do the same thing as the audio stream.

**Comment by rerrahkr** [comment]
I changed them at 09410a2d0aba61c837c20d4c4f999d875ed7f1c2.

**Comment by OPNA2608** [comment]
Fixed, many thanks. :rocket:
