### ISSUE TITLE
[GTK-Linux|BSD] - File importer doesn't see files with upper-case extensions

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#338]
> #### Checklist
> 
> 
> 
> - [X] I am reporting exactly 1 bug with this issue.
> - [X] This bug hasn't already been reported.
> - [X] This bug hasn't already been fixed in the latest development build.

---

## Bug Description

~This bug is similiar to #317 in that it happens only on specific Linux desktop environments, making it very hard to debug. I only know GNOME and XFCE sufer from that~. Steps to reproduce:
1. Right click and select "Import from bank format"
2. Navigate to directory when files in *.PVI, *.PZI or .*FF formats are (it turns out it's upper-case extension files that don't load, *.pvi for example is OK)
3. You won't see them. In order to be able to import then you must drag and drop a bank into BT's import window, and then you will see files of _every_ format, including executables, images, music files, etc.
![Zrzut ekranu z 2021-02-19 11-19-44](https://user-images.githubusercontent.com/32672779/108493111-3f798c00-72a6-11eb-9b1e-b195862d0a2c.png)

**Comment by EnfauKerus** [comment]
this is an upstream issue  
https://gitlab.gnome.org/GNOME/gtk/-/issues/1347  
https://github.com/flatpak/xdg-desktop-portal/issues/225

**Comment by freq-mod** [comment]
So, it's a problem with gtk and not BambooTracker?

**Comment by EnfauKerus** [comment]
very likely  
![GtkFileChooserSucks](https://cdn.discordapp.com/attachments/769177992471511126/812301857972158474/unknown.png)

**Comment by OPNA2608** [comment]
Since this is a problem with code that BT has no direct influence over, I think the easiest way to handle this is to use the `QFileDialog::DontUseNativeDialog` option on Linux & BSD, but with an option to override this decision either permanently via a compile-time `CONFIG` setting or temporarily with a runtime environment variable. This'll use the known-good Qt file picker by default, but allows users who'd really prefer the GTK-based one to temporarily test if it works for them and permanently recompile the program without this limitation if they don't mind the drawbacks.

Alternatively, the `getExtension()` & file reading/saving code could be modified/expanded to translate the regular all-lowercase extensions (`"ff"`) in the code to a regex pattern that both Qt's and GTK's dialogues seem to understand to some degree (`"[fF][fF]"`). This may require additional code changes to fix saving with an automatic extension though, since Qt appears to not translate such a pattern into regular text, instead appending `.[fF][fF]` to files where it's tasked to automatically add an extension.

**Comment by rerrahkr** [comment]
I'll use `QFileDialog::DontUseNativeDialog`, which is easy to implement. The compilation options are left untouched for simplicity.

Qt provides OS identifiers in [QtGlobal](https://doc.qt.io/qt-5/qtglobal.html) which contains `Q_OS_*BSD`.
To be honest, I don't know much about BSD. Is the "BSD" we've been talking about so far in this project FreeBSD, NetBSD, or OpenBSD?

**Comment by freq-mod** [comment]
> Is the "BSD" we've been talking about so far in this project FreeBSD, NetBSD, or OpenBSD?

yes, "BSD" is a general term for BSD Unix derivatives like FreeBSD, OpenBSD, etc
