### ISSUE TITLE
[Feature] - Improve "envelope reset before key-on" function

### ISSUE THREAD

**Issue by freq-mod** [rerrahkr/BambooTracker#362]
> #### Checklist
> 
> 
> 
> - [X] I'm requesting exactly 1 feature with this issue.
> - [ ] This feature hasn't already been requested.
> - [X] This feature hasn't already been implemented in the latest development build.

---

## Requested Feature

Hello. After talking to some people, I feel this instrument parameter can be improved somewhat. One user requested:

- replacing the function with an actual note cut, which completely stops the instrument
- adding two new effects basing on that. First would behave the same way as "envelope reset" and use the note cuts..
- and another one that would do the same thing, but for the release.

That way, you can turn it on or off as you please. How do you feel about it? Is it viable? Or is everything outlined above possible already?

**Comment by rerrahkr** [comment]
Sorry I'm not sure I understand your request. My understanding is that "Envelope reset" or "Envelope reset before key on" does an "actual note cut".
Both of these initialize the envelope, but there is no such function in the hardware of the YM2608, so the following procedure does it:

1. note off as usual.
2. immediately afterwards, set the RR (Release Rate) of the FM envelope parameter to 0. This will set the envelope back to 0.
3. restore the RR at the next note on.

---

And by an effect that does a note cut or release, do you mean something that does a note cut or release before x counts of the next note on, similar to the `q` command in many MMLs? This is a feature that I considered adding very early on. (533c3af733cc6cd87a65b7301d19a66df574562e, a6874a2088d5eadd2e0864c6556f15899184399f)
BambooTracker dynamically changes the step size in order to match the tempo with the playback speed. It is difficult to find out when the next note-on is x-counts away, so I abandoned the implementation.
Since the step size is always guaranteed to be greater than 1, it can only determine if the current time is one count before the next note on.

The "Envelope reset before key on" function is intended to ensure that the envelope of the next note rises normally. So-called "Only key off before key on" is not effective for this purpose, so I didn't implement it.

**Comment by freq-mod** [comment]
Well, user that originally suggested that thought that envelope reset works by forcing the rr values to 15 (and sl values to 7?) before each note. Seems like it's not the case, then.

>, do you mean something that does a note cut or release before x counts of the next note on, similar to the q command in many MMLs?

idk :man_shrugging: .Probably q command-like option, but if it's impossible, than Ok, never mind.
