### ISSUE TITLE
[FR] i18n capabilities (ie: French and German translations proposed)

### ISSUE THREAD

**Issue by trebmuh** [rerrahkr/BambooTracker#50]
Hi, I would like to provide a French translation for the GUI, but it seems that there isn't a way of doing so yet. Could you please add it?

**Comment by OPNA2608** [comment]
Yes, i18n capabilities would be neat! I could provide a German translation, if that helps with catching interest :smiley:

**Comment by rerrahkr** [comment]
Thanks!
It seems that [Qt can translate](http://doc.qt.io/qt-5/internationalization.html).
First I will try to see if it works.

**Comment by trebmuh** [comment]
Sweet, let me know how it goes.

**Comment by jpcima** [comment]
>It seems that Qt can translate.
First I will try to see if it works.

I'm able to help with i18n programming in Qt, you can assign me this task if you want.
@trebmuh is an ace translator, he can handle the rest. :smiley:

**Comment by rerrahkr** [comment]
Thanks @jpcima, its very helpful! Unfortunately I can hardly work for the tracker since I must do another tasks for a while.
I fixed texts in f958afaa91c8d0a76930f2c33ced43aa7da21964 and make Japanese .ts file to use lupdate whitch extracts them and Qt Linguist which translate them to Japanese.  in L10n_ja branch 9d67346b78de5d1e94d0cba57ca18756ea949947. But I have not made .qm 
and load yet.

**Comment by trebmuh** [comment]
Closing here since it has been done.
Thanks people!
