### ISSUE TITLE
[Enhancement] Implement retrieving channel state during playback

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#58]
Steps to replicate:

1. Open a module :http://cherry.dhcp.phys.ethz.ch/majfant2quieter.btm
2. Play it
3. Edit the first instrument by changing FB value to 0
4. Hit play button once again.
5. With any luck, the song will become much louder, almost like every instrument was playing at max volume

**Comment by rerrahkr** [comment]
Does it only happen when the current order number is "02" or later in the song?
BambooTracker resets all chip registers before starting song play. Since there are not volume event in the head of orders after "02", the song play at initial max volume.
I also have an idea retrieving channel states in playing, so I will implement it in future.

**Comment by papiezak** [comment]
>BambooTracker resets all chip registers before starting song play. Since there are not volume event in the head of orders after "02", the song play at initial max volume.

Damn, I didn't notice there are only volume events at the beginning of the song. My bad, but if you said you will work around it anyway, I may not close the issue

**Comment by rerrahkr** [comment]
I finally implement retrieving channel state in 71e22c5f1f8bebad94e191bf243485c0ea7057c8.

**Comment by papiezak** [comment]
I see, thanks a lot!
