### ISSUE TITLE
[Idea] Automated CI build deployment

### ISSUE THREAD

**Issue by papiezak** [rerrahkr/BambooTracker#65]
Looking at a discussion fa213ae there is a need for that.
Compiling from source on Windows is a chore, compared to Linux distros, since:
-there is no centralized package manager for distributing development libraries (Qt?)
-MinGW/MSYS can be a hassle

CI (continuous integration) services like AppVeyor can be used to test/build source code on Windows VM and then deploy the fresh devbuilds in binary form without a need to wait for a full release.
https://www.appveyor.com/docs/

**Comment by OPNA2608** [comment]
Compiling from source on Windows should actually be pretty straightforward. I don't think BambooTracker has any extra dependencies on Windows, so this should work:

1) Install [Qt](https://www.qt.io/download-qt-installer). Make sure to tick the MinGW checkbox during the installation if you don't have another C++ compiler installed.
2) In your Start Menu, under "Qt" will now be a shortcut to a cmd environment with Qt and MinGW all set up. Start it.
3) Navigate to your local clone of BambooTracker.
4)
```
qmake
mingw32-make install
```

If you also want to be able to start BambooTracker from the explorer instead of this cmd environment:

5) Navigate to your BambooTracker installation directory. (either supplied to qmake with PREFIX or the default according to BambooTracker.pro)
6)
```
windeployqt BambooTracker.exe
```

Regardless, CI would be neat for those who can't be bothered to do all of this. :+1:

**Comment by jpcima** [comment]
Example can be taken from our project with Qt and Appveyor.

https://github.com/Wohlstand/OPL3BankEditor/blob/master/appveyor.yml
https://github.com/Wohlstand/OPL3BankEditor/blob/master/build.bat

**Comment by papiezak** [comment]
Looks like it's done, CI dev build is running, thanks @rerrahkr!
