### ISSUE TITLE
Suggestion: default/selectable mixing presets

### ISSUE THREAD

**Issue by ImATrackMan** [rerrahkr/BambooTracker#72]
When exporting a file, Bamboo auto-fills the "System" box with PC-9801. This isn't necessary accurate.

When FM/SSG levels are matched, it's nearly exactly the same as an OPNA with no resistor on the SSG output and no amplification. On initial startup, Bamboo's 0/0 mixing is similar (if not the same as) a PC-88 with a Sound Board 2. With the SSG set to -3dB relative to FM, the output is again, very similar to (if not the same as) a PC-9801-86 board and one of my own Makoto boards for MSX. Makoto uses Yamaha's suggestion of a 470 ohm pulldown on the SSG output, and it's likely that the -86 does as well, making this the "proper" PC-98 mixing level.

Adding Mix Select boxes in the module properties menus for Sound Board 2 and 9801-86/Makoto guarantees proper sound when playing .vgm or .S98 on hardware with these platforms without a user having to enter the menu and reset it themselves.

This does not mean the options for arbitrary mixing should be removed, only to add selections for proper hardware levels.

**Comment by rerrahkr** [comment]
Thanks for your request.
I planned on implementing that function before, however, I postponed it because I did not have information of volume balance between FM and SSG.

The current SSG "0dB" means that you don't amplify SSG wave generated by MAME (in VGMPlay). I have to check if the volume balance is really equal.

I also find SSG mix settings of [hoot](http://dmpsoft.s17.xrea.com/) and [documents about volume balance](https://www12.atwiki.jp/touhousoundfont/pages/18.html#id_4585e2f0). Although I have not understood the settings value mean of hoot, they say:

|settings|ssg_mix (hoot)|SSG relative ratio against FM|
|---|---|---|
|PC-8801FA (with Sound Board 2?)|-2|50%|
|PC-88VA2 (with Sound Board 2?)|-4|55%|
|PC-9821 with PC-9801-86|-18|25%|
|PC-9821 with Speak Board|-13|30%|
|PC-9821 with OTOMICHAN|-13|65%|

I'm not confirmed these are correct, but I think to refer to them as well as your information.

**Comment by rerrahkr** [comment]
I researched the relationship between ssg_mix of hoot, volume of SSG emulation of fmgen (hoot uses) and BambooTracker's MAME and Nuked OPN-Mod. It seemed that hoot set 4 - ssg_mix to `OPNA::SetVolumePSG(int db)` in fmgen. SSG volume of fmgen is changed by `db` * 0.5 dB, so after comparing FM and SSG volume of fmgen with MAME and Nuked, I calculated the expected the volume of SSG when FM is 0dB.

I updated the SSG volume table in previous comment with estimated mixer levels. I will probably create a select box with these values.

**Comment by rerrahkr** [comment]
At 330131956a4bfe7991fcf43ce8e29342b4738548, I added the mixer settings in the module properties.

If "Mixer" is checked, the mixer values of the module is valid. Otherwise,  the configuration mixer is used as before.
The module mixer has 5 mixer type: Custom, PC-9821 with PC-9801-86, PC-9821 with Speak Board, PC-88VA2 and PC-8801mkIISR. You can change the levels of Custom mixer to edit configuration mixer before pressing "Set" button.

I set PC-9821 with PC-9801-86 as the default mixer after module v1.3.0 and let the tracker use the comfiguration mixer when loading an old module.

**Comment by rerrahkr** [comment]
It's difficult to improve mixing settings at this time. I may work on new improvements in the future if we get information on the actual sound board.
