### ISSUE TITLE
Crackling noises

### ISSUE THREAD

**Issue by Ikalou** [rerrahkr/BambooTracker#77]
Hi,

I don't know if this is an issue with BambooTracker, the MAME emulation of the chip, or my own setup, but I'm getting a lot of crackling noises with slow attacks on modulators.

Here is a comparison between BambooTracker and VOPM (I know they aren't exactly the same chip):

![image](https://user-images.githubusercontent.com/3008001/54241625-dcabe180-4521-11e9-9769-dc2c807c46bd.png)

WAV: [bamboo.zip](https://github.com/rerrahkr/BambooTracker/files/2959037/bamboo.zip)

![image](https://user-images.githubusercontent.com/3008001/54241644-ed5c5780-4521-11e9-80fe-057e54d7dc21.png)

WAV: [vopm.zip](https://github.com/rerrahkr/BambooTracker/files/2959038/vopm.zip)

Is this expected? Any idea how to make it better?

**Comment by rerrahkr** [comment]
Thanks for report. I checked this envelope in a real YM2608 chip.
[real.zip](https://github.com/rerrahkr/BambooTracker/files/2961971/real.zip)
It also gets some noise, so it seems expected behavior.
If you would like to avoid getting noises, I think increasing TL of modulator is one of the solutions.

**Comment by Ikalou** [comment]
Thank you for taking the time to check on hardware. And the you for the advice.

I had been using vopm and I noticed BambooTracker was noisier in some situations, but if it's more accurate to the hardware then all the better.
